Citizen.CreateThread(function()
    -- Drift
    local tun = GetInteriorAtCoordsWithType(1176.157, -3193.703, -9.278,"uj_tuner_car_meet2") 
    EnableInteriorProp(tun, "set1")
    EnableInteriorProp(tun, "set2")
    EnableInteriorProp(tun, "set3")
    EnableInteriorProp(tun, "set4")
    EnableInteriorProp(tun, "set5")
    EnableInteriorProp(tun, "set6")
    EnableInteriorProp(tun, "set7")
    EnableInteriorProp(tun, "set8")
    EnableInteriorProp(tun, "set9")
    RefreshInterior(tun)

    -- Meth
    local interiorIDMETH = GetInteriorAtCoordsWithType(-147.7690, 6303.5957, 24.569, "int_stock")
    RefreshInterior(interiorIDMETH)
    EnableInteriorProp(interiorIDMETH, "meth_app")
    EnableInteriorProp(interiorIDMETH, "meth_staff_01")
    EnableInteriorProp(interiorIDMETH, "meth_staff_02")
    EnableInteriorProp(interiorIDMETH, "meth_basic_lab_01")
    EnableInteriorProp(interiorIDMETH, "meth_basic_lab_02")
    EnableInteriorProp(interiorIDMETH, "meth_basic_lab_01_2")
    EnableInteriorProp(interiorIDMETH, "meth_basic_lab_02_2")
    EnableInteriorProp(interiorIDMETH, "weed_basic_lamp")
    EnableInteriorProp(interiorIDMETH, "meth_stock")

    -- Weed
    local interiorIDWEED = GetInteriorAtCoordsWithType(2862.444, 4456.0014, 41.322, "int_stock")
    RefreshInterior(interiorIDWEED)
    EnableInteriorProp(interiorIDWEED, "weed_app")
    EnableInteriorProp(interiorIDWEED, "weed_staff_01")
    EnableInteriorProp(interiorIDWEED, "weed_staff_02")
    EnableInteriorProp(interiorIDWEED, "weed_basic_lamp")
    EnableInteriorProp(interiorIDWEED, "weed_fan_basick")
    EnableInteriorProp(interiorIDWEED, "weed_stock")
    EnableInteriorProp(interiorIDWEED, "weed_plant_v5")

    -- Oxy
    local interiorIDOXY = GetInteriorAtCoordsWithType(1397.311, -2092.379, 45.499, "int_stock")
    RefreshInterior(interiorIDOXY)
    EnableInteriorProp(interiorIDOXY, "coke_app")
    EnableInteriorProp(interiorIDOXY, "coke_staff_01")
    EnableInteriorProp(interiorIDOXY, "coke_staff_02")
    EnableInteriorProp(interiorIDOXY, "coke_stock")

    -- Wash
    local interiorIDMWASH = GetInteriorAtCoordsWithType(2536.508,4118.2700,31.460, "int_stock")
    EnableInteriorProp(interiorIDMWASH, "weed_basic_lamp")
    EnableInteriorProp(interiorIDMWASH, "money_app")
    EnableInteriorProp(interiorIDMWASH, "money_staff_02")
    EnableInteriorProp(interiorIDMWASH, "money_stock")

    -- Weapon
    local interiorIDWEAPON = GetInteriorAtCoordsWithType(-326.7500, -1356.434, 31.295, "int_stock")
    EnableInteriorProp(interiorIDWEAPON, "weed_basic_lamp")
    EnableInteriorProp(interiorIDWEAPON, "weapon_app")
    EnableInteriorProp(interiorIDWEAPON, "weapon_staff_01")
    EnableInteriorProp(interiorIDWEAPON, "weapon_stock")

    -- Pillbox
    RequestIpl("gabz_pillbox_milo_")
    local PillboxInt = GetInteriorAtCoords(311.2546, -592.4204, 42.32737)
    RemoveIpl("rc12b_fixed")
    RemoveIpl("rc12b_destroyed")
    RemoveIpl("rc12b_default")
    RemoveIpl("rc12b_hospitalinterior_lod")
    RemoveIpl("rc12b_hospitalinterior")
    RefreshInterior(PillboxInt)

    RequestIpl("gabz_mrpd_milo_")
    local interiorID = GetInteriorAtCoords(451.0129, -993.3741, 29.1718)
    if IsValidInterior(interiorID) then      
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm1")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm2")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm3")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm4")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm5")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm6")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm7")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm8")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm9")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm10")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm11")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm12")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm13")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm14")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm15")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm16")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm17")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm18")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm19")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm20")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm21")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm22")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm23")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm24")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm25")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm26")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm27")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm28")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm29")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm30")
        EnableInteriorProp(interiorID, "v_gabz_mrpd_rm31")
        RefreshInterior(interiorID)
    end
end)

local function getInterriorByType(x, y, z, name, iplName)
	local id = 0

	if not IsIplActive(iplName) then
		RequestIpl(iplName)

		while not IsIplActive(iplName) do
			RequestIpl(iplName)
			Wait(100)
		end
	end

	while id == 0 do
		id = GetInteriorAtCoordsWithType(x, y, z, name)
		Wait(100)
	end

	return id
end

Citizen.CreateThread(function()
	RequestIpl("vw_casino_penthouse")
	RequestIpl("hei_dlc_windows_casino")
	local penthouse = getInterriorByType(976.6364,70.2947,115.1641,"vw_dlc_casino_apart", "vw_casino_penthouse")
	local uj_casino_vault = getInterriorByType(946.251,43.2715,58.9172,"uj_casino_vault", "uj_casino_vault_milo_")
	local uj_casino_main = getInterriorByType(935.1050,42.5656,71.2737,"uj_casino_main", "uj_casino_main_milo_")
	local uj_casino_back = getInterriorByType(974.5600,22.5161,70.8396,"uj_casino_back", "uj_casino_back_milo_")
	local uj_casino_tunnel = getInterriorByType(930.1539,-0.2010,59.1323,"uj_casino_tunnel", "uj_casino_tunnel_milo_")

	EnableInteriorProp(penthouse, "set_pent_tint_shell")
	DisableInteriorProp(penthouse, "set_pent_bar_party_1")  
	EnableInteriorProp(penthouse, "set_pent_media_bar_open")
	EnableInteriorProp(penthouse, "set_pent_spa_bar_open")
	EnableInteriorProp(penthouse, "set_pent_dealer")
	DisableInteriorProp(penthouse, "set_pent_nodealer")
	DisableInteriorProp(penthouse, "set_pent_media_bar_closed")
	DisableInteriorProp(penthouse, "set_pent_spa_bar_closed")
	DisableInteriorProp(penthouse, "set_pent_pattern_01")
	DisableInteriorProp(penthouse, "set_pent_pattern_03")
	DisableInteriorProp(penthouse, "set_pent_pattern_02")
	DisableInteriorProp(penthouse, "set_pent_pattern_04")
	DisableInteriorProp(penthouse, "set_pent_pattern_05")
	DisableInteriorProp(penthouse, "set_pent_pattern_06")
	DisableInteriorProp(penthouse, "set_pent_pattern_07")
	DisableInteriorProp(penthouse, "set_pent_pattern_08")
	EnableInteriorProp(penthouse, "set_pent_pattern_09")
	DisableInteriorProp(penthouse, "set_pent_arcade_modern")
	EnableInteriorProp(penthouse, "set_pent_arcade_retro")
	EnableInteriorProp(penthouse, "set_pent_clutter_03")
	EnableInteriorProp(penthouse, "set_pent_clutter_02")
	EnableInteriorProp(penthouse, "set_pent_clutter_01")
	DisableInteriorProp(penthouse, "set_pent_lounge_blocker")
	DisableInteriorProp(penthouse, "set_pent_guest_blocker")
	DisableInteriorProp(penthouse, "set_pent_office_blocker")
	DisableInteriorProp(penthouse, "set_pent_cine_blocker")
	DisableInteriorProp(penthouse, "set_pent_spa_blocker")
	DisableInteriorProp(penthouse, "set_pent_bar_blocker")
	DisableInteriorProp(penthouse, "set_pent_bar_party_after")
	DisableInteriorProp(penthouse, "set_pent_bar_clutter")
	EnableInteriorProp(penthouse, "set_pent_bar_party_2")
	DisableInteriorProp(penthouse, "set_pent_bar_light_0")
	DisableInteriorProp(penthouse, "set_pent_bar_light_01")
	DisableInteriorProp(penthouse, "set_pent_bar_light_02")
	DisableInteriorProp(penthouse, "set_pent_bar_party_0")
	DisableInteriorProp(penthouse, "set_pent_bar_party_1")

    SetInteriorEntitySetColor(penthouse,"set_pent_tint_shell","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_bar_party_1","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_tint_shell","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_media_bar_open","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_spa_bar_open","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_dealer","0") -- Дверцы
    SetInteriorEntitySetColor(penthouse, "set_pent_nodealer","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_media_bar_closed","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_spa_bar_closed","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_pattern_01","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_pattern_03","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_pattern_02","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_pattern_04","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_pattern_05","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_pattern_06","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_pattern_07","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_pattern_08","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_pattern_09","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_arcade_modern","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_arcade_retro","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_clutter_03","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_clutter_02","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_clutter_01","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_lounge_blocker","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_guest_blocker","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_office_blocker","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_cine_blocker","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_spa_blocker","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_bar_blocker","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_bar_party_after","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_bar_clutter","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_bar_party_2","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_bar_light_0","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_bar_light_01","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_bar_light_02","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_bar_party_0","0")
    SetInteriorEntitySetColor(penthouse, "set_pent_bar_party_1","0")
	RefreshInterior(penthouse)

	EnableInteriorProp(uj_casino_vault, "set_vault_diamonds_02")
	EnableInteriorProp(uj_casino_vault, "set_vault_diamonds_01")
	EnableInteriorProp(uj_casino_vault, "set_vault_gold_02")
	EnableInteriorProp(uj_casino_vault, "set_vault_gold_01")
	EnableInteriorProp(uj_casino_vault, "set_vault_art_02")
	EnableInteriorProp(uj_casino_vault, "set_vault_art_01")
	EnableInteriorProp(uj_casino_vault, "set_vault_cash_02")
	EnableInteriorProp(uj_casino_vault, "set_vault_cash_01")
	EnableInteriorProp(uj_casino_vault, "set_vault_dressing")
	EnableInteriorProp(uj_casino_vault, "set_spawn_group2")
	EnableInteriorProp(uj_casino_vault, "set_spawn_group1")
	DisableInteriorProp(uj_casino_vault, "set_vault_door_broken")
	EnableInteriorProp(uj_casino_vault, "set_vault_door")
	DisableInteriorProp(uj_casino_vault, "set_vault_door_closed")
	RefreshInterior(uj_casino_vault)

	EnableInteriorProp(uj_casino_main, "casino_manager_default")
	EnableInteriorProp(uj_casino_main, "casino_manager_workout")
	RefreshInterior(uj_casino_main)

	EnableInteriorProp(uj_casino_back, "casino_back_laundry_damage")
	RefreshInterior(uj_casino_back)
	
	EnableInteriorProp(uj_casino_tunnel, "set_tunnel_collapse")
	RefreshInterior(uj_casino_tunnel)
end)