function AddTextEntry(key, value)
    Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

CreateThread(function()
    AddTextEntry("4runner", "Toyota 4Runner")
    AddTextEntry("CHALLENGER", "Dodge Challenger")
    AddTextEntry("CHARGER", "Dodge Charger")
    AddTextEntry("20trailboss", "Silverado ZR1")
    AddTextEntry("XMAX400", "Yamaha XMAX")
    AddTextEntry("21s8", "Audi S8 Custom")
    AddTextEntry("GMC", "GMC Sierra Custom")
    AddTextEntry("68firebird", "Pontiac Firebird 1968")
    AddTextEntry("86karma", "Toyota GT-86 Karma")
    AddTextEntry("180sx", "Nissan 180sx")
    AddTextEntry("cb500x", "Honda CB500")
    AddTextEntry("600lt", "McLaren 600lt")
    AddTextEntry("PRIMO", "Mercedes 600sel")
    AddTextEntry("675LTSP", "McLaren 675lt Spyder")
    AddTextEntry("812gts", "Ferrari 812 GTS")
    AddTextEntry("911R", "Prosche 911R")
    AddTextEntry("1016urus", "Lamborghini Urus")
    AddTextEntry("1500ghoul", "Dodge RAM Ghoul")
    AddTextEntry("TOPCAR DESIGN", "Brabus G900")
    AddTextEntry("adamlzs15", "Silvia S15 Drift")
    AddTextEntry("AE86", "Toyota AE86")
    AddTextEntry("aeroxdrag", "Yamaha Aerox")
    AddTextEntry("AFRICAT", "Africa Twin")
    AddTextEntry("AGERARS", "Koenigsegg Agera RS")
    AddTextEntry("alphd3525", "Toyota Alphard Custom")
    AddTextEntry("amggt320", "Mercedes AMG GT3")
    AddTextEntry("AMGGTRR20", "Mercedes AMG GTR")
    AddTextEntry("anubis", "Mazda RX7 Anubis")
    AddTextEntry("s200", "Honda S2000")
    AddTextEntry("BARRACUDA", "Barracuda Polisi")
    AddTextEntry("DIVO 2019", "Buggati Divo")
    AddTextEntry("beetleRWB", "VW Beetle RWB")
    AddTextEntry("bentaygaplsd", "Bentley Bentayga Custom")
    AddTextEntry("bmw", "Bmw X7")
    AddTextEntry("bmwm2h", "Bmw M2 Custom")
    AddTextEntry("bmwm4", "Bmw M4 Custom")
    AddTextEntry("BMWM6GT3", "Bmw M6 GT3")
    AddTextEntry("bnr34", "Nissan GT-R34")
    AddTextEntry("BOSS302", "Mustang Boss 302")
    AddTextEntry("C7", "Corvette C7")
    AddTextEntry("C10CUSTOM", "Chevrolet C10 Custom")
    AddTextEntry("c63coupe", "Mercedes AMG C63 Coupe")
    AddTextEntry("c63hr", "Mercedes AMG C63 Custom")
    AddTextEntry("carry", "Suzuki Carry Drift")
    AddTextEntry("CBR650R", "Honda CBR650r")
    AddTextEntry("CH-R", "Toyota C-HR")
    AddTextEntry("claw", "HarleyDavidson BreakOut")
    AddTextEntry("contss18c", "Bentley Continental")
    AddTextEntry("COUNTACH", "Lamborghini Countach")
    AddTextEntry("crf", "Honda CRF")
    AddTextEntry("crv", "Honda CR-V")
    AddTextEntry("DAWNONYX", "Rolls Royce Dawn")
    AddTextEntry("db1117", "Aston Martin DB11")
    AddTextEntry("Desmosedici GP20", "Ducati Desmosedici")
    AddTextEntry("DemonHawk", "Jeep DemonHawk")
    AddTextEntry("dtdautobio", "Range Rover Custom")
    AddTextEntry("dtdbolide", "Buggati Bolide Custom")
    AddTextEntry("e350taxi", "Mercedes Taxi")
    AddTextEntry("erka1", "Pagani Huayra Custom")
    AddTextEntry("EVO9", "Mitsubishi Evo 9")
    AddTextEntry("evopol", "Evo Polisi")
    AddTextEntry("EVO VARIS", "Mitsubishi Evo 9")
    AddTextEntry("f8lb", "Ferrari F8 LibertyWalk")
    AddTextEntry("F150", "Raptor F150")
    AddTextEntry("AVENTADOR", "Aventador Ems")
    AddTextEntry("CALIFORNIAT", "Ferrari California")
    AddTextEntry("Filthy", "Acura Nsx Filthy")
    AddTextEntry("FK8", "Honda Civic FK8")
    AddTextEntry("fk8hr", "Honda Civic FK8 Custom")
    AddTextEntry("FOCUSRS", "Ford Focus RS")
    AddTextEntry("foxct", "Tesla CyberTruck")
    AddTextEntry("foxsterrato", "Lamborghini Sterrato")
    AddTextEntry("ftrds", "Toyota Fortuner")
    AddTextEntry("fz07", "Yamaha MT7")
    AddTextEntry("G63AMG6x6", "AMG 6x6 Polisi")
    AddTextEntry("G650", "Mercedes Maybach G650")
    AddTextEntry("gcmaveu", "Lamborghini Aventador Custom")
    AddTextEntry("gemera1", "Koenigsegg Gemera")
    AddTextEntry("ghispo2", "Maserati Polisi")
    AddTextEntry("gk4", "Honda Jazz GK4")
    AddTextEntry("gls600", "Mercedes Maybach GLS 600")
    AddTextEntry("gs1", "Bms GS1200")
    AddTextEntry("gs310", "Bmw GS310")
    AddTextEntry("GSX R1000R", "Suzuki GSX R1000R")
    AddTextEntry("gsxrr", "Suzuki GSX GP")
    AddTextEntry("gt295", "Porsche 911 RWB")
    AddTextEntry("GT63SAMG", "Mercedes AMG GT63S")
    AddTextEntry("GTR", "Nissan GT-R35")
    AddTextEntry("gtr35kreamc", "Nissan GT-R35 Custom")
    AddTextEntry("GTZ34", "Nissan GT-r34 Drift")
    AddTextEntry("h2carb", "Ninja H2 Carbon")
    AddTextEntry("hbrimob", "Hummer Polisi")
    AddTextEntry("HCBR17", "Honda CBR1000r")
    AddTextEntry("HDIron883", "HarleyDavidson Iron 883")
    AddTextEntry("NINEF", "Fat Boy Lo Racing Bobber")
    AddTextEntry("hilux6x6", "Toyota Hilux 6x6")
    AddTextEntry("eg6", "Honda Estilo")
    AddTextEntry("hoonitruck", "HooniTruck")
    AddTextEntry("hornet52", "Hudson Hornet 1952")
    AddTextEntry("hummerevdub", "Hummer EV Custom")
    AddTextEntry("huralb", "Lamborghini Huracan LB")
    AddTextEntry("S560", "Apollo")
    AddTextEntry("ilusi", "Toyota Supra 2020 Custom")
    AddTextEntry("STI", "Subaru Impreza")
    AddTextEntry("innova21mg", "Kijang Innova")
    AddTextEntry("innovajatanras", "Innova Mekanik")
    AddTextEntry("jazz", "Honda Jazz")
    AddTextEntry("jeepg", "Jeep Gladiator")
    AddTextEntry("jes", "Koenigsegg Jesko")
    AddTextEntry("jes21", "Koenigsegg Jesko Custom")
    AddTextEntry("Wrangler", "Jeep Rubicon")
    AddTextEntry("jukehr1", "Nissan Juke Custom")
    AddTextEntry("Chaser", "Toyota Chaser")
    AddTextEntry("kia", "KIA Stinger GT Custom")
    AddTextEntry("KLX 150", "Klx Polisi")
    AddTextEntry("KLX 151", "Klx ems")
    AddTextEntry("SuperDuke", "KTM SuperDuke R1290")
    AddTextEntry("LAFERRARI17", "Ferrari LaFerrari Custom")
    AddTextEntry("lancer57", "Royal Lancer")
    AddTextEntry("LWHURACAN", "Lamborghini Huracan LW")
    AddTextEntry("lc500", "Lexus LC 500")
    AddTextEntry("looni", "Toyota Alphard")
    AddTextEntry("LP700R", "Lamborghini Aventador")
    AddTextEntry("lummaq8", "Audi Q8")
    AddTextEntry("M3F80", "Bmw M3 F80")
    AddTextEntry("M3G80C", "Bmw M3 G80")
    AddTextEntry("M4C", "Bmw M4 Cabriolet")
    AddTextEntry("m4", "Bmw M4 LB")
    AddTextEntry("m6prior", "Bmw M6 Prior")
    AddTextEntry("m8gte", "Bmw M8 GTE")
    AddTextEntry("Z33", "Nissan Fairlady Z350")
    AddTextEntry("M8", "Bmw M8 Mansaug")
    AddTextEntry("MARK1", "Maxwell Mark 1")
    AddTextEntry("mazda6", "Mazda Polisi")
    AddTextEntry("300SL", "Mercedes 300SL Gullwing")
    AddTextEntry("mbbs20", "Mercedes AMG GT BlackSeries")
    AddTextEntry("MCJCW20", "Mini Cooper")
    AddTextEntry("mercedesbenz", "Mercedes AMG E55")
    AddTextEntry("MODELS", "Tesla Model S Custom")
    AddTextEntry("mustang", "Ford Mustang")
    AddTextEntry("dm1200", "Ducati Multistrada")
    AddTextEntry("mvso", "Ducati MV Agusta")
    AddTextEntry("mx5326", "Mazda MX5 Camber")
    AddTextEntry("nsx", "Honda Nsx")
    AddTextEntry("na25", "HarleyDavidson RoadKing")
    AddTextEntry("nc750x", "Honda NC750")
    AddTextEntry("NinjaH2", "Ninja H2r")
    AddTextEntry("S13", "Nissan Silvia S13")
    AddTextEntry("nis15", "Nissan Silvia S15")
    AddTextEntry("nissantitan17", "Nissan Titan")
    AddTextEntry("e-tron_GT", "Audi E-Tron GT")
    AddTextEntry("osusraptord", "Ford Raptor Custom")
    AddTextEntry("P1", "McLaren P1")
    AddTextEntry("GTR ROAD LEGAL", "McLaren P1 GTR")
    AddTextEntry("Porsche Panamera", "Porsche Panamera")
    AddTextEntry("Phantom8EWB", "Rolls Royce Phantom")
    AddTextEntry("BLISTA", "Pika Car")
    AddTextEntry("pista", "Ferrari 488 Pista Spyder")
    AddTextEntry("BO105", "Heli Polisi")
    AddTextEntry("PORSCHE911TARGA", "Porsche 911 TARGA")
    AddTextEntry("r1", "Yamaha R1")
    AddTextEntry("r820", "Audi R8")
    AddTextEntry("r25", "Yamaha R25")
    AddTextEntry("RVFF", "Radiant VFF")
    AddTextEntry("range_brimob", "Range Rover EMS")
    AddTextEntry("RAPTOR2017", "Ford Raptor 2017")
    AddTextEntry("rc", "Nissan Patrol")
    AddTextEntry("RD", "HarleyDavidson RedDevil")
    AddTextEntry("rmod240sx", "Nissan 240sx")
    AddTextEntry("rmod918spyder", "Porsche 918 Spyder")
    AddTextEntry("rmodamgc63", "Mercedes AMG C63")
    AddTextEntry("rmodatlantic", "Bugatti Atlantic")
    AddTextEntry("rmodbolide", "Bugatti Bolide")
    AddTextEntry("rmodbugatti", " Bugatti LaVoitureNoire")
    AddTextEntry("rmodc63amg", "Mercedes AMG C63")
    AddTextEntry("rmodf40", "Ferrari F40")
    AddTextEntry("rmodgt63", "Mercedes AMG GT63")
    AddTextEntry("rmodgtr50", "Nissan GT-R50")
    AddTextEntry("rmodi8ks", "Bmw I8 Custom")
    AddTextEntry("rmodm4", "BMW M4")
    AddTextEntry("rmodm4gts", "BMW M4 GTS")
    AddTextEntry("rmodm8c", "BMW M8 Cabriolet")
    AddTextEntry("rmodmi8lb", "BMW M8 LibertyWalk")
    AddTextEntry("rmodpagani", "Pagani Huayra")
    AddTextEntry("rmodrover", "Land Rover")
    AddTextEntry("rmodsennagtr", "McLaren Senna GTR")
    AddTextEntry("rmodskyline34", "Nissan Skyline R34")
    AddTextEntry("rmodspeed", "McLaren SpeedTail")
    AddTextEntry("rmodsupra", "Toyota Supra MK-IV")
    AddTextEntry("rmodsuprapandem", "Toyota Supra Pandem")
    AddTextEntry("rmodz350pandem", "Nissan Z350 Pandem")
    AddTextEntry("rmodzl1", "Camaro ZL1")
    AddTextEntry("rr68cuda", "Plymouth HEMI CUDA")
    AddTextEntry("RS7C8WB", "Audi RS7 Custom")
    AddTextEntry("RS666", "Audi RS6 Custom")
    AddTextEntry("RX7TUNABLE", "Mazda RX7")
    AddTextEntry("rx811", "Mazda RX8")
    AddTextEntry("S2000pm", "Honda S2000 Custom")
    AddTextEntry("s15urashr", "Nissan Silvia S15 Custom")
    AddTextEntry("S30", "Nissan Fairlady S30")
    AddTextEntry("S63C", "Mercedes S63C")
    AddTextEntry("S500W222", "Mercedes W222 S500")
    AddTextEntry("s1000rr", "Bmw S1000rr")
    AddTextEntry("sc18", "Lamborghini SC18")
    AddTextEntry("SCIJO", "Volkswagen Scirocco")
    AddTextEntry("SENNA", "McLaren Senna")
    AddTextEntry("SIAN ROADSTER", "Lamborghini Sian Roadster")
    AddTextEntry("Slave", "Slave")
    AddTextEntry("Corvette C8", "Corvette C8")
    AddTextEntry("SUPRA2", "Toyota Supra")
    AddTextEntry("sxr", "Bmw S1000 XR")
    AddTextEntry("TAKI428", "Ford Shelby GT500")
    AddTextEntry("tenere1200", "Yamaha Tenere 1200")
    AddTextEntry("teslapd", "Tesla PriorDesign")
    AddTextEntry("tit1", "Toyota Camry Custom")
    AddTextEntry("tonkatruck", "Toyota Hilux")
    AddTextEntry("TOY86", "Toyota GT-86")
    AddTextEntry("TRITONHP", "Mitsubishi Triton")
    AddTextEntry("tritonlantas", "Triton Polisi")
    AddTextEntry("TSGR20", "Toyota Supra 2020")
    AddTextEntry("TWISTER 250 PARAGON", "Twister Paragon 250")
    AddTextEntry("ursa", "Porsche Macan ursa")
    AddTextEntry("URUS", "Lamborghini Urus")
    AddTextEntry("v4sf", "Ducati V4 StreetFighter")
    AddTextEntry("V4 Speciale", "Ducati V4 Speciale")
    AddTextEntry("velociraptor", "Ford Velociraptor")
    AddTextEntry("VENATUS", "Lamborghini Urus")
    AddTextEntry("Verin", "LCC Verin")
    AddTextEntry("vespa1", "Vespa Sprinter")
    AddTextEntry("VSRX7", "Mazda RX7 Veilside")
    AddTextEntry("wald2018", "Lexus Wald LX570")
    AddTextEntry("wildtrak", "Ford Bronco")
    AddTextEntry("wolf1", "Riot Polisi")
    AddTextEntry("X1", "RedBull X1")
    AddTextEntry("X6M", "BMW X6M F16")
    AddTextEntry("x6pol", "BMW X6M Polisi")
    AddTextEntry("xt700", "Yamaha Xt700")
    AddTextEntry("Yaris Rocket Bunny", "Yaris RocketBunny")
    AddTextEntry("yzfr6", "Yamaha R6")
    AddTextEntry("z4alchemist", "Bmw Z4 Alchemist")
    AddTextEntry("BMWZ4", "Bmw Z4 Cabriolet")
    AddTextEntry("z1000", "Kawasaki Z1000")
    AddTextEntry("zcrk", "Pagani Huayra Custom")
    AddTextEntry("ZENTENARIO", "Lamborghini Zentenario")
    AddTextEntry("ZX10R", "Kawasaki ZX-10R")
    AddTextEntry("foxharley2", "HarleyDavidson RoadGlide")
    AddTextEntry("ninja250fi", "Kawasaki Ninja 250fi")
    AddTextEntry("foxharley1", "HarleyDavidson StreetBob")
    AddTextEntry("356ac", "Porsche 356 Speedster")
    AddTextEntry("rmodcharger69", "Dodge Charger")
    AddTextEntry("AVANZA", "Toyota Avanza")
    AddTextEntry("FXXKEVO", "Ferrari FXXK EVO")
    AddTextEntry("m8f91", "Bmw M8 F91")
    AddTextEntry("SF1000", "F1 Ferrari")
    AddTextEntry("W11", "F1 W11")
    AddTextEntry("m52ncs", "BMW M5 Competition")
    AddTextEntry("21durango", "Bmw M4 Competition")
    AddTextEntry("isfhr", "Lexus LS F")
    AddTextEntry("G800Gold", "Brabus G900 BlackGold")
    AddTextEntry("g63widemod", "Mercedes G63 Wide")
    AddTextEntry("fc7", "Honda Civic FC7")
    AddTextEntry("ESCALADESPORT", "Cadillac Escalade")
    AddTextEntry("E63SVG", "Mercedes Benz E63")
    AddTextEntry("CCX", "Koenigsegg CCX")
    AddTextEntry("kr150", "Ninja KR150")
    AddTextEntry("CAVCADE", "Pajero")
    AddTextEntry("PATRIOT", "H1")
    AddTextEntry("BMW X7", "BMW X7")
    AddTextEntry("900SS", "Ducati 900ss")
    AddTextEntry("terzo", "Lamborghini Terzo")
    AddTextEntry("ONE", "Mercedes AMG One")
    AddTextEntry("hallostang", "Shelby Mustang")
    AddTextEntry("20r11", "Yamaha R1M")
    AddTextEntry("h22carb", "Kawasaki H2r")
    AddTextEntry("HCBR177", "Honda CBR1000rr")
    AddTextEntry("jes211", "Koenigsegg Jesko")
    AddTextEntry("s1000rrr", "BMW S1000rr")
    AddTextEntry("ZX10RRR", "Kawasaki ZX10r")
end)
