-----------------For support, scripts, and more----------------
--------------- https://discord.gg/wasabiscripts  -------------
---------------------------------------------------------------

Strings = {

    -- Go on/off duty new
    on_duty = 'On Duty',
    on_duty_desc = 'You have just switched to on duty!',
    off_duty = 'Off Duty',
    off_duty_desc = 'You have just switched to off duty!',

    -- QbCore support (1.3.0)
    amount = 'Amount',
    mr = 'Mr',
    mrs = 'Mrs',
    debt_collection = 'Debt Collection',
    db_email = 'Dear %s %s, <br /><br />The Central Judicial Collection Agency (CJCA) charged the fines you received from the police.<br />There is <strong>$%s</strong> withdrawn from your account.<br /><br />Kind regards,<br />Mr. Wasabi',
    fine_sent = 'Fines Sent',
    fine_sent_desc = 'You have successfully sent fine for $%s!',
    fine_received = 'Fine Received',
    fine_received_desc = 'You have received a fine for $%s',

    -- Death discord logs (1.2.9)
    log_killed_title = 'Player Killed',
    log_killed_desc = '> *%s [%s] killed %s [%s]\n\n**Killer\'s Information:**\nName: `%s`\nPlayer ID: `%s`\nIdentifier: `%s`\nSteam: `%s`\nDiscord: `%s`\nLicense: `%s`\nLicense2: `%s`\nXBL: `%s`\nFiveM: `%s`\nIP: ||%s||\n\n**Victim\'s Information:**\nCharacter Name: `%s`\nPlayer ID: `%s`\nIdentifier: `%s`\nSteam: `%s`\nDiscord: `%s`\nLicense: `%s`\nLicense2: `%s`\nXBL: `%s`\nFiveM: `%s`\nIP: ||%s||\n\n> **Death Cause:** `%s`',
    log_suicide_title = 'Player Committed Suicide',
    log_suicide_desc = '> %s [%s] killed themselves\n\n**Player Information:**\nName: `%s`\nPlayer ID: `%s`\nIdentifier: `%s`\nSteam: `%s`\nDiscord: `%s`\nLicense: `%s`\nLicense2: `%s`\nXBL: `%s`\nFiveM: `%s`\nIP: ||%s||\n\n> **Death Cause:** `%s`',
    unknown = 'UNKNOWN',


    -- Revive discord logs (1.4.6)
    log_admin_revive_title = 'Player Admin Revived',
    log_admin_revive_desc = '> *%s [%s] admin revived %s [%s]\n\n**Target\'s Information:**\nName: `%s`\nPlayer ID: `%s`\nIdentifier: `%s`\nSteam: `%s`\nDiscord: `%s`\nLicense: `%s`\nLicense2: `%s`\nXBL: `%s`\nFiveM: `%s`\nIP: ||%s||\n\n**Admin\'s Information:**\nCharacter Name: `%s`\nPlayer ID: `%s`\nIdentifier: `%s`\nSteam: `%s`\nDiscord: `%s`\nLicense: `%s`\nLicense2: `%s`\nXBL: `%s`\nFiveM: `%s`\nIP: ||%s||',
    log_self_revive_title = 'Admin Self Revived',
    log_self_revive_desc = '> %s [%s] self revived\n\n**Player Information:**\nName: `%s`\nPlayer ID: `%s`\nIdentifier: `%s`\nSteam: `%s`\nDiscord: `%s`\nLicense: `%s`\nLicense2: `%s`\nXBL: `%s`\nFiveM: `%s`\nIP: ||%s||',
    log_death_logs = 'Death Logs',
    log_revive_logs = 'Revive Logs',

    medbag_crutch = 'Crutch',
    medbag_crutch_desc = 'A crutch to assist patients with walking',
    menu_crutch = 'Apply Crutch',
    menu_crutch_desc = 'Add a crutch to a nearby patient',

    -- Wheelchair strings(1.2.8)
    medbag_chair = 'Wheelchair',
    medbag_chair_desc = 'A wheelchair to assist patients who cannot walk',
    menu_chair = 'Apply Wheelchair',
    menu_chair_desc = 'Add a wheelchair to a nearby patient',
    --end


    shot = 'shot',
    stabbed = 'stabbed',
    beat = 'beat',
    burned = 'burned',
    other = 'Other',

    JobMenuTitle = 'EMS Menu',
    dispatch = 'Dispatch',
    dispatch_desc = 'Check for players in need of assistance',
    DispatchMenuTitle = 'Dispatch',
    GoBack = 'Go Back',
    key_map_text = 'Ambulance Job Menu',
    assistance_title = 'Assistance Requested',
    assistance_desc = 'A person has requested medical assistance!',
    respawn_available_in = 'Respawn available in ~b~%s minutes %s seconds~s~\n',
    respawn_bleedout_in = 'You will bleed out in ~b~%s minutes %s seconds~s~\n',
    respawn_bleedout_prompt = 'Hold [~b~E~s~] to respawn',
    distress_send = 'Press [~b~G~s~] to send distress signal to EMS',
    distress_sent_title = 'Assistance Requested',
    distress_sent_desc = 'Distress signal has been sent to available units!',
    route_set_title = 'Route Set',
    route_set_desc = 'A waypoint has been set to the distressed person!',
    diagnose_patient = 'Diagnose',
    diagnose_patient_desc = 'Diagnose the closest injured person',
    no_requests = 'No active requests',
    revive_patient = 'Revive',
    revive_patient_desc = 'Attempt to revive nearby person',
    heal_patient = 'Heal',
    heal_patient_desc = 'Attempt to heal nearby person',
    sedate_patient = 'Sedate',
    sedate_patient_desc = 'Temporarily sedate nearby person',
    drag_patient = 'Drag',
    drag_patient_desc = 'Drag nearby injured person',
    place_stretcher_target = 'Add or Remove Patient',
    place_patient = 'Place In/Out Vehicle',
    place_patient_desc = 'Place nearby person in/out of vehicle',
    no_nearby = 'Not Found',
    no_nearby_desc = 'There appears to be nobody around',
    no_injury = 'No Injury',
    no_injury_desc = 'Person doesn\'t appear to need any additional treatment',
    player_injury = 'Person Injured',
    player_injury_desc = 'This person has appeared to have been %s',
    player_not_unconcious = 'Player Concious',
    player_not_unconcious_desc = 'It appears the player is concious',
    player_unconcious = 'Player Unconcious',
    player_unconcious_desc = 'Patient is required to be concious for this treatment!',
    player_reviving = 'Reviving',
    player_reviving_desc = 'Reviving patient in progress',
    player_noitem = 'Missing Item',
    player_noitem_desc = 'You lack the required item for this!',
    player_successful_revive = 'Revived',
    player_successful_revive_reward_desc = 'You have successfully revived the patient and earned $%s!',
    player_successful_revive_desc = 'You have successfully revived the patient!',
    player_healing = 'Healing',
    player_healing_desc = 'Healing patient in progress',
    player_successful_heal = 'Healed',
    player_successful_heal_desc = 'Patient successfully healed!',
    player_healed_desc = 'You have been successfully healed by the medic!',
    not_medic = 'Unauthorized',
    not_medic_desc = 'You are not trained to use this!',
    target_sedated = 'Sedated',
    target_sedated_desc = 'You have been sedated by a medical professional',
    player_successful_sedate_desc = 'You have successfully sedated the patient',
    drop_bag_ui = '[E] - Drop Bag',
    drop_stretch_ui = '[E] - Place Stretcher',
    pickup_bag_target = 'Pick Up',
    move_target = 'Move',
    interact_bag_target = 'Open',
    successful = 'Successful',
    medbag_pickup = 'You picked up the medbag',
    medbag_pickup_civ = 'You searched the bag and have taken what would be of use',
    stretcher_pickup = 'You picked up the foldable stretcher',
    medbag = 'Medical Bag',
    medbag_tweezers = 'Tweezers',
	medbag_tweezers_desc = 'Used to remove bullets',
	medbag_suture = 'Suture Kit',
    medbag_suture_desc = 'Used to stitch wounds',
    medbag_icepack = 'Ice Pack',
    medbag_icepack_desc = 'Used to reduce swelling',
    medbag_burncream = 'Burn Cream',
    medbag_burncream_desc = 'Used to treat burns',
    medbag_defib = 'Defibrillator',
    medbag_defib_desc = 'For reviving patients',
    medbag_medikit = 'Medkit',
    medbag_medikit_desc = 'Digunakan untuk Revive Korban',
    medbag_sedative = 'Sedative',
    medbag_sedative_desc = 'Used to sedate patients',
--    medbag_stretcher = 'Foldable Stretcher',
--    medbag_stretcher_desc = 'Used for moving patients',
--    item_grab = 'You have pulled a tool from your medical bag',
--    wrong_equipment = 'Wrong Equipment!',
--    wrong_equipment_desc = 'Have you even been trained?',
    player_not_injured = 'Not Injured',
    player_not_injured_desc = 'This person does not appear to need any extra treatment and is clear for the defibrillator',
    player_treated = 'Treated',
    player_treated_desc = 'You have successfully treated the patient',
    revive_command_help = 'An admin command to revive players',
    revive_command_arg = 'The player id',
    reviveall_command_help = 'An admin command to revive every player',
    revivearea_command_help = 'An admin command to revive nearby players',
    revivearea_command_arg = 'Area to revive players',
    resetdeathcount_command_help = 'An admin command to reset players deathcount',
    resetdeathcount_command_arg = 'The player id',
    viewdeathcount_command_help = 'A command to view your deathcount',
    alive_again = 'Alive',
    alive_again_desc = 'You were dropped off by a local at the hospital!',
    request_supplies_target = 'Medical Supplies',
    currency = '$',
    not_enough_funds = 'Insufficient Funds',
    not_enough_funds_desc = 'You don\'t have enough funds!',
    hospital_garage = 'Hospital Garage',
    used_meditkit = 'Medkit Used',
    used_medikit_desc = 'You\'ve managed to patch yourself up',
    action_cancelled = 'Action Cancelled',
    action_cancelled_desc = 'You cancelled your last action!',
    healing_self_prog = 'Treating Wounds',
    checkin_hospital = 'Success',
    checkin_hospital_desc = 'You have been successful treated by the hospital staff',
    max_ems = 'Medics Avaliable',
    max_ems_desc = 'There are plenty of medics in the city! Distress for help!',
    player_busy = 'Busy',
    player_busy_desc = 'You are currently too busy to do this action!',
    cloakroom = 'Changing Room',
    civilian_wear = 'Civilian Wear',
    bill_patient = 'Bill Patient',
    bill_patient_desc = 'Send a nearby patient an invoice',
    invalid_entry = 'Invalid',
    invalid_entry_desc = 'Your entry was invalid!',
    medical_services = 'Medical Services',
    hospital = 'Hospital',

    interact_stretcher_ui = '[E] - Interact',
    stretcher_menu_title = 'Stretcher Interactions',
    open_shop_ui = '[E] - Open Pharmacy',
    
}
